### ISSUE TITLE
Buy land to stop expand of the city

### ISSUE THREAD

**Issue by filipchudoba** [voxeltycoon/suggestions#199]
Sometimes it is annoying if i want to build factory and I have no space for it, so this can be a prevention.

**Comment by victorleblais** [comment]
How do you think this feature could be implemented in the current UI?
How would bought land look like?

As a workaround, you can build decorations top prevent the city from expanding, something like pumpkins would work.

**Comment by JezzyBelle** [comment]
I like this concept. I have seen companies buy large tracts of land like that outside of cities. Better to hold land than have to demolish homes and businesses for later expansion.
I am no programmer.. just a gamer. So here's my take on implementation.

Implementation: 
Purchasing land would be in blocks... IE: think the shape of your potential businesses and the footprint they need.  So, with that in mind, may need to be a few sizes. Image would be very similar to what territories we have not unlocked look like. IE: Border demarcation and also some shading. Otherwise, it would act just like a building. You would pay some limited regular fees for upkeep, etc until you utilize it. I also think there should be a timer. So, you only reserve it for a given time then it reverts and you suffer a penalty in the form of losing a deposit or something..... So, in effect, you do not own it. You just purchased an option to buy.
