### ISSUE TITLE
Transfer passengers and goods

### ISSUE THREAD

**Issue by LaChRiZ** [voxeltycoon/suggestions#207]
The orders menu should contain the type "transfer". (like in OpenTTD https://wiki.openttd.org/en/Manual/Orders#transfer)
That means that all passengers (or goods) will be unloaded, but not sold. They remain at the station for another train/vehicle.
And the player got a little amount of money for the transfer.

**Typical situation**
If the first train station in the town is to small to handle more trains, and you won't make it bigger or delete city buildings, you could build another, bigger station outside the town. To feed this station with passengers you pick up all pessengers from the first station and transfer it to the bigger one. And from there the passengers are transported to the next city.

This also solves the problem of the small catchment areas (or influence area?) of the stations. Buildings outside this area could be reached by another station (e.g. a bus stop) that carries passengers to the main train station.

**Comment by polak-jan** [comment]
This is already possible with goods using warehouses, but as far I am aware it's not with passangers, but is most definitely planned as the passanger system is brand new and will evolve quite a bit over time.

Marking as "already implemented" and closing because of the goods part and due to the same for passangers being either planned or already being worked on.
