### ISSUE TITLE
Game shouldn't go back to speed one when a business goes backrupt

### ISSUE THREAD

**Issue by Samuel38** [voxeltycoon/suggestions#220]
**Describe the suggestion**
When a business goes bankrupt, the game goes back to speed 1. 
There is no point in this behavior, since it's already to late to do anything about it, and since most of the time, these are businesses where the player has no access to the ressource. 
If it was intended to slow down, it should do so when the business is about to go bankrupt, not when it did. 
And it definitely shouldn't if the product is locked behind research or regions at the time.

**Comment by Fredrik-Leftin** [comment]
That's a feature. Whenever you get a red notification, the speed is set to 1. This feature gives you the ability to solve the related problem.

**Comment by JezzyBelle** [comment]
It may be a feature but perhaps set it to return to last setting after a certain duration so that player is not required to interact to retrun to normal speed? OR... have it as an option a player can disable in the game settings. 
In my opinion, the game should just run, run, run. It's a living world! They only reason it should stop is because you pause or shut down.

If necessary, you could have a temp "Attention required" icon that remains after the initial warning splash screen that needs to be dismissed.

Scenario: I have all tweaked and running good. Want to walk away and let it run for a bit so I can accumulate some wealth after tweaking it. 

Current: Really? It went into slow speed the whole time I was gone over that!?!!

Fix: Oh hey, something went on while I was away that needs my attention! (click icon to read). "Yeah, maybe that was a bad idea to leave it running. That explains why I now longer have a viable lumber business in Sad Town"

---------------------------------------------
But what if it ruined everything for some reason? 

Answer: Had you not disabled that setting (default is to have the existing behavior) or simply paused/saved the game... You took the risk. You are playing real life now baby!... Life doesn't just stop for you while you are picking up more chips from the store. Expect a train wreck and a few failed businesses if you walk away!

**Comment by Fredrik-Leftin** [comment]
I got your point of view and having both the features could be the best option. You may create a suggestion about it.

**Comment by andrewpey** [comment]
With [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1) we've introduced a setting allowing a player to disable this behavior.
