### ISSUE TITLE
"Reversed Pre Signals"

### ISSUE THREAD

**Issue by CapMJK** [voxeltycoon/suggestions#234]
Hello,
as is the signals are very limited which is a problem in a train simulator. I have seen path signals are on the road map but what about the second type of pre signals that are also missing? Currently pre signals are red when any signal in the block ahead is red. There should be a type that is only be red when ALL signals in a block ahead are red since they are used to prevent blockage on a crossing normally. There is currently no way to have meaningfull multiplattform station settings.

**Comment by polak-jan** [comment]
I am not sure I understand what you are saying properly, but from what I do you are probably using signals wrong. Because the behaviour you are asking for is the current behaviour of pre-signals, they are yellow when any of the signals ahead are red, and red when all of them are red.

So I am closing this issue, but if I am misunderstanding you please do comment bellow with clarifications, and if you need help with getting the signals to work I would recommend joining the official Discord server and asking there.

**Comment by CapMJK** [comment]
leave it closed. It seems i hit a bug that somehow did not trigger yellow if one signal is green. My pre signal stayed red until all were green. now it works in the same setup as it should.
