### ISSUE TITLE
繁琐的操作

### ISSUE THREAD

**Issue by oThTJx** [voxeltycoon/suggestions#301]
这个选择停靠点和线路真的很繁琐,既然能给站点命名,
可不可以加个搜索,然后以下拉选框形式进行选择停靠点
选择线路能不能加个搜索,几十条线路很难筛选,
道路建设能不能智能一点,地形高低就会导致无法建设道路,高架或者隧道以快捷键方式实现,不要去点下边的功能菜单,很繁琐的,可以参考天际线,

**Comment by scailman** [comment]
This choice of stops and routes is really cumbersome. Since the site can be named,
Can you add a search, and then select the stop in the form of a drop-down box
Can you add a search to select the line? It is difficult to filter dozens of lines.
Can the road construction be smarter? The terrain will lead to the inability to build roads. The elevated or tunnel can be realized by shortcut keys. Don't click the function menu below. It is very cumbersome. You can refer to the skyline.

**Comment by andrewpey** [comment]
Please split this to separate suggestions.
