### ISSUE TITLE
Select buildings a station/terminal sells to

### ISSUE THREAD

**Issue by hurzelchen** [voxeltycoon/suggestions#50]
**Is your feature request related to a problem? Please describe.**
If you have a rail station close a city but always want to go the "last mile" by truck it might happen that the train station already sells to the store with reduced profit. This especially happens when the city grows towards your station.

**Describe the solution you'd like**
Give the player a list of business within reach to tick on/off if goods should be sold to them. Default yes for all for new stations/businesses.

**Comment by victorleblais** [comment]
Another solution, would be to have more order options for vehicles similar to how OpenTTD handles this same issue.

In OpenTTD, this issue of "not wanting to sell right now" is solved by using the order "transfer cargo" instead of "unload cargo".

"Unload" will try to sell goods and "Transfer" won't.

**Comment by hurzelchen** [comment]
That is even better as it would give control not only per station but per route/vehicle.

**Comment by andrewpey** [comment]
Not the case since 
[0.85](https://voxeltycoon.xyz/changelog#0.85)
